// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSWXGT3Zy3M5Y4wWMoW4TEpy8lAb_niBY',
    appId: '1:822860341232:web:9ea5cc3ac6f62b54870735',
    messagingSenderId: '822860341232',
    projectId: 'flutter-minimalist-chat-app',
    authDomain: 'flutter-minimalist-chat-app.firebaseapp.com',
    storageBucket: 'flutter-minimalist-chat-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvBNXaB_LWZ5fQzXHuJN5171s-TzYQ3EQ',
    appId: '1:822860341232:android:bee6328e3d0d5f6b870735',
    messagingSenderId: '822860341232',
    projectId: 'flutter-minimalist-chat-app',
    storageBucket: 'flutter-minimalist-chat-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMCtJ1yhzzqi6Q-iGZfCAOVYPqwdLRvPo',
    appId: '1:822860341232:ios:18c941b8373638b6870735',
    messagingSenderId: '822860341232',
    projectId: 'flutter-minimalist-chat-app',
    storageBucket: 'flutter-minimalist-chat-app.firebasestorage.app',
    iosBundleId: 'com.example.minimalistChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMCtJ1yhzzqi6Q-iGZfCAOVYPqwdLRvPo',
    appId: '1:822860341232:ios:18c941b8373638b6870735',
    messagingSenderId: '822860341232',
    projectId: 'flutter-minimalist-chat-app',
    storageBucket: 'flutter-minimalist-chat-app.firebasestorage.app',
    iosBundleId: 'com.example.minimalistChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSWXGT3Zy3M5Y4wWMoW4TEpy8lAb_niBY',
    appId: '1:822860341232:web:51c1e6f91e2283c3870735',
    messagingSenderId: '822860341232',
    projectId: 'flutter-minimalist-chat-app',
    authDomain: 'flutter-minimalist-chat-app.firebaseapp.com',
    storageBucket: 'flutter-minimalist-chat-app.firebasestorage.app',
  );
}
